<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="f450">
  <!-- Parameters -->
  <xacro:property name="frame_radius" value="0.5"/>   <!-- ~450mm diagonal => ~225mm arm half-length -->
  <xacro:property name="body_radius"  value="0.09"/>    <!-- central plate radius -->
  <xacro:property name="body_height"  value="0.03"/>
  <xacro:property name="body_mass"    value="0.5"/>     <!-- tweak with real mass -->
  <xacro:property name="arm_mass"     value="0.08"/>
  <xacro:property name="blade_mass"   value="0.03"/>
  <xacro:property name="motor_mass"   value="0.03"/>

  <!-- Inertial helper -->
  <xacro:macro name="inertial_cylinder" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- Solid cylinder about z-axis -->
      <inertia
        ixx="${(1.0/12.0)*m*(3*r*r + h*h)}"
        iyy="${(1.0/12.0)*m*(3*r*r + h*h)}"
        izz="${0.5*m*r*r}"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </xacro:macro>

<!-- Inertial helper for box -->
  <xacro:macro name="inertial_box" params="m l w h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- Solid box (rectangular prism) -->
      <inertia
        ixx="${(1.0/12.0)*m*(h*h + w*w)}"
        iyy="${(1.0/12.0)*m*(h*h + l*l)}"
        izz="${(1.0/12.0)*m*(l*l + w*w)}"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </xacro:macro>

  <!-- Base link (central plate) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.10 0.10 0.05"/></geometry>
      <material name="dark_gray"><color rgba="0.25 0.25 0.25 0.98"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.10 0.10 0.07"/></geometry>
    </collision>
    <xacro:inertial_box m="${body_mass}" l="0.10" w="0.10" h="0.07"/>
  </link>

<!-- Arms + motor + rotors (x4) -->
<xacro:macro name="arm_with_rotor" params="name angle color_name color_rgba">

    <!-- arm link -->
    <link name="${name}_arm">
      <visual>
        <origin xyz="${frame_radius/4} 0 0" rpy="0 0 0"/>  <!-- Offset = half of arm length -->
        <geometry><box size="${frame_radius/2} 0.02 0.02"/></geometry>  <!-- 25cm long -->
        <material name="${color_name}"><color rgba="${color_rgba}"/></material>
      </visual>
      <collision>
        <origin xyz="${frame_radius/4} 0 0" rpy="0 0 0"/>
        <geometry><box size="${frame_radius/2} 0.02 0.02"/></geometry>
      </collision>
      <inertial>
        <origin xyz="${frame_radius/4} 0 0" rpy="0 0 0"/>
        <mass value="${arm_mass}"/>
        <inertia ixx="0.0005" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="base_to_${name}_arm" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
      <parent link="base_link"/>
      <child link="${name}_arm"/>
    </joint>


    <!-- motor at arm tip -->
    <link name="${name}_motor">
      <visual>
        <origin xyz="${frame_radius/2.0-0.011} 0 0.0175" rpy="0 0 0"/>
        <geometry><cylinder radius="0.010" length="0.035"/></geometry>
        <material name="red"><color rgba="1.0 0.0 0.0 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="${frame_radius/2.0-0.011} 0 0.0175" rpy="0 0 0"/>
        <geometry><cylinder radius="0.015" length="0.035"/></geometry>
      </collision>
      <inertial>
        <origin xyz="${frame_radius/2.0} 0 0.0" rpy="0 0 0"/>
        <mass value="${motor_mass}"/>
        <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <!-- blade at arm tip -->
    <link name="${name}_blade">
      <visual>
        <origin xyz="${frame_radius/2.0-0.011} 0 0.045" rpy="0 0 0"/>
        <geometry><cylinder radius="0.11" length="0.005"/></geometry>
        <material name="grey"><color rgba="0.6 0.6 0.6 0.2"/></material>
      </visual>
      <collision>
        <origin xyz="${frame_radius/2.0-0.011} 0 0.045" rpy="0 0 0"/>
        <geometry><cylinder radius="0.11" length="0.005"/></geometry>
      </collision>
      <inertial>
        <origin xyz="${frame_radius/2.0} 0 0.045" rpy="0 0 0"/>
        <mass value="${blade_mass}"/>
        <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name}_arm_to_motor" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_arm"/>
      <child link="${name}_motor"/>
    </joint>

    <joint name="${name}_motor_to_blade" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_motor"/>
      <child link="${name}_blade"/>
    </joint>
  </xacro:macro>

<xacro:arm_with_rotor name="front_right" angle="${-45 * 3.14159265/180.0}" 
                      color_name="arm_front_right" color_rgba="1.0 0.0 0.0 1.0"/>
<xacro:arm_with_rotor name="front_left"  angle="${45 * 3.14159265/180.0}" 
                      color_name="arm_front_left" color_rgba="1.0 0.0 0.0 1.0"/>
<xacro:arm_with_rotor name="rear_right"  angle="${-135 * 3.14159265/180.0}" 
                      color_name="arm_rear_right" color_rgba="0.0 0.0 0.0 1.0"/>
<xacro:arm_with_rotor name="rear_left"   angle="${135 * 3.14159265/180.0}" 
                      color_name="arm_rear_left" color_rgba="0.0 0.0 0.0 1.0"/>
</robot>