<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="f450">
  <!-- Parameters -->
  <xacro:property name="frame_radius" value="0.225"/>   <!-- ~450mm diagonal => ~225mm arm half-length -->
  <xacro:property name="body_radius"  value="0.09"/>    <!-- central plate radius -->
  <xacro:property name="body_height"  value="0.03"/>
  <xacro:property name="body_mass"    value="0.5"/>     <!-- tweak with real mass -->
  <xacro:property name="arm_mass"     value="0.08"/>
  <xacro:property name="rotor_mass"   value="0.03"/>

  <!-- Inertial helper -->
  <xacro:macro name="inertial_cylinder" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- Approximate inertia for solid cylinder (about center, z as axis) -->
      <inertia
        ixx="${(1/12.0)*m*(3*r*r + h*h)}"
        iyy="${(1/12.0)*m*(3*r*r + h*h)}"
        izz="${0.5*m*r*r}"/>
    </inertial>
  </xacro:macro>

  <!-- Base link (central plate) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="${body_radius}" length="${body_height}"/></geometry>
      <material name="black"><color rgba="0.1 0.1 0.1 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="${body_radius}" length="${body_height}"/></geometry>
    </collision>
    <xacro:inertial_cylinder m="${body_mass}" r="${body_radius}" h="${body_height}"/>
  </link>

  <!-- Arms + rotors (x4) -->
  <xacro:macro name="arm_with_rotor" params="name angle">
    <!-- arm link -->
    <link name="${name}_arm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${frame_radius} 0.02 0.02"/></geometry>
        <material name="red"><color rgba="0.8 0.1 0.1 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${frame_radius} 0.02 0.02"/></geometry>
      </collision>
      <inertial>
        <origin xyz="${frame_radius/2} 0 0" rpy="0 0 0"/>
        <mass value="${arm_mass}"/>
        <inertia ixx="0.0005" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="base_to_${name}_arm" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
      <parent link="base_link"/>
      <child link="${name}_arm"/>
    </joint>

    <!-- rotor at arm tip -->
    <link name="${name}_rotor">
      <visual>
        <origin xyz="${frame_radius} 0 0.015" rpy="0 0 0"/>
        <geometry><cylinder radius="0.11" length="0.005"/></geometry>
        <material name="grey"><color rgba="0.6 0.6 0.6 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="${frame_radius} 0 0.015" rpy="0 0 0"/>
        <geometry><cylinder radius="0.11" length="0.005"/></geometry>
      </collision>
      <inertial>
        <origin xyz="${frame_radius} 0 0.015" rpy="0 0 0"/>
        <mass value="${rotor_mass}"/>
        <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name}_arm_to_rotor" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_arm"/>
      <child link="${name}_rotor"/>
    </joint>
  </xacro:macro>

  <xacro:arm_with_rotor name="front_right" angle="${-45 * 3.14159265/180.0}"/>
  <xacro:arm_with_rotor name="rear_right"  angle="${-135 * 3.14159265/180.0}"/>
  <xacro:arm_with_rotor name="rear_left"   angle="${135 * 3.14159265/180.0}"/>
  <xacro:arm_with_rotor name="front_left"  angle="${45 * 3.14159265/180.0}"/>

</robot>